### PR TITLE
Implement new slide-in main menu

### PR DESCRIPTION
**Pull request by TehMillhouse**
The new menu doesn't obstruct the editor window, and can safely be left
open while developing lambda terms. This allows us to simply leave the
library reference open, and allow multiple term info panels to be
expanded at the same time.
Of course, this means the slide-in menu will need to be scrollable if it
gets too large. However, this is deemed fine, as users would expect this
behavior from a slide-in menu (unlike from a pop-up).

lol

The sliding animation is done in pure CSS, and since this change enables multiple `TermInfo`s being open at once, the `ToggleTermInfo` machinery isn't needed anymore.

### CODE REVIEW

**Comment by mhuisi** [comment]
I think that a slide-in would improve the application.

Some questions about this proposal:
- Is there a particular reason why the slide-in has a dark theme, as opposed to a light theme like the rest of the application?
- Why is the main menu button a label as opposed to a button? (cursor doesn't change to indicate that the button is clickable, clickable region feels kind of off)

Some additional thoughts:
- The contrast of the term info should be higher
- Enabling the scroll bar by displaying a term info should not move the buttons that enable/disable term infos
- Exercise buttons should be indented
- Clickable region for exercise buttons should fill the full width of the menu
- There shouldn't be a non-clickable space between exercise buttons

What do you think?

**Comment by TehMillhouse** [comment]
> Is there a particular reason why the slide-in has a dark theme, as opposed to a light theme like the rest of the application?

Personal aesthetic preference. I find that a light slide-in would need an ugly border to properly stand apart from the main application window, and I wanted to avoid that.

> Why is the main menu button a label as opposed to a button? (cursor doesn't change to indicate that the button is clickable, clickable region feels kind of off)

I wanted to keep the interaction with the menu purely in CSS, and that was easier to achieve with a hidden checkbox and a label. I initially tried getting it to work with a button and `:target`, but that got rather clumsy. The cursor and clickable region can be fixed.

> The contrast of the term info should be higher
> Enabling the scroll bar by displaying a term info should not move the buttons that enable/disable term infos
> Exercise buttons should be indented
> Clickable region for exercise buttons should fill the full width of the menu
> There shouldn't be a non-clickable space between exercise buttons

ACK to all of these. Will implement them.

**Edit: Done.**

**Comment by mhuisi** [comment]
On Firefox 59.0.2 the new menu looks like this: 
img

Is it intended to look like this?

Looking at the CSS (especially the new pseudo-element in particular) I am also unsure whether implementing the menu in pure CSS is such a good idea, especially considering that it's inconsistent with the way the rest of the application is implemented.

Thoughts?

Other than this the new menu looks like it's almost ready to be merged.

**Comment by TehMillhouse** [comment]
Latest commit fixes the firefox issue. Apart from both browsers using different checkboxes, the look and feel of the new menu is now consistent across both firefox and chrome.

I'm not convinced that implementing it in java would result in prettier code, but I agree that such CSS hacks should probably be documented. I'll do that in an upcoming commit.

**Comment by mhuisi** [comment]
LGTM except for a few minor style inconsistencies (exercise buttons not yet indented, main menu button has no hover background highlighting, horizontal scroll shouldn't show up when vertical space is exceeded).

There's also something that I can't quite put my finger on: On Windows the font in the menu looks quite a lot rougher than in your preview (see my FF screenshot earlier, for instance), presumably because of Windows' font rendering, which doesn't look as rough on white surfaces (so the rest of the UI seems smoother).
However, I don't this is worth fixing, as I am not even sure if it is easily fixable with CSS.

Those inconsistencies are pretty minor, though, and if you wish I can merge your current changes without those inconsistencies being addressed.

**Comment by mhuisi** [comment]
LGTM. I made a tiny final change by removing the transition animation from the main menu button.
I'll merge the PR now.

**Pull request merged**
