### PR TITLE
Add "plug diagrams" output

### PR DESCRIPTION
**Pull request by TehMillhouse**
I've been trying to come up with a representation of lambda calculus that is actually sort of intuitive (and entirely free of reptilians), and this is the result:
screenshot from 2018-11-27 17-05-36
screenshot from 2018-11-27 17-29-35

After getting the go ahead to make additional slides for propa and spending entirely too long fiddling around in inkscape, I decided to instead rather spend a day implementing a renderer in Wavelength.

In case you can't tell, an application `x y` becomes `(x 〈 y)`, bound variables become arrows pointed to from their binder, and lambdas are turned into sort-of-pacman-things and floated to the right. Every redex is immediately recognizable, and capture avoidance, malformed parentheses and alpha conversion simply disappear by construction. The arrows even tell you what you need to do.
You're left with diagrams that are easy to interpret and "execute" even without knowing anything about lambda calculus (hopefully).
screenshot from 2018-11-27 17-06-07
`PartialApplication`s gain an additional prime character with each argument they absorb, and crossing arrows are helpfully visually separated
screenshot from 2018-11-27 17-07-09
The renderer is more than fast enough for reasonable inputs...
screenshot from 2018-11-27 17-20-47
and unreasonable inputs.
screenshot from 2018-11-27 16-46-42
There's no highlighting of the current redex, and no clickable redexes yet, and I don't know if I'll ever get around to adding them, seeing as I've made this mostly to make it easier to generate slides. The code is mostly trivial, though there's at least one good match for using visitors that I was too lazy to implement. Now that the layouting framework is there, implementing a faster, denser tree output is probably quite easy, but I'll leave that as an exercise to the reader.

EDIT: They're already deployed on [our server](https://pp.ipd.kit.edu/lehre/misc/lambda-ide/Wavelength.html) (the link for that instance changed btw, you'll want to change the repo's description), if you want to play around with it.

### CODE REVIEW

**Comment by mhuisi** [comment]
It looks like the "revert reduction" function doesn't work as expected for plug diagrams.
It always reverts two steps at once, which leads to "revert reduction" not actually returning to the initial UI state when the UI output is empty.
EDIT: As far as I can tell, the URL in the description is exactly the same as the one you linked. (Not sure if someone changed it in the mean time)

**Comment by TehMillhouse** [comment]
Good catch! Will investigate. (When I checked, the link in the description pointed to /lehre/WS201819/..., so it seems someone else took care of it)

**Comment by TehMillhouse** [comment]
New version [is live](https://pp.ipd.kit.edu/lehre/misc/lambda-ide/Wavelength.html), has redex highlighting and manual selection support.

**Comment by mhuisi** [comment]
(Browser: Chrome 70.0.3538.110)
I'm not sure if I'm missing something, but I can't spot any redex highlighting or indicators for manual selection in plug diagrams in the live version.

Unicode output redex highlighting for the next term that the selected reduction order will select appears to be broken as well.

Is this logging call intended, or is that a debugging leftover?
https://github.com/wavelength-ide/wavelength-ide/pull/63/files#diff-1ca476972e9c3d17427c59e85a99db24R86

**Comment by TehMillhouse** [comment]
I'm guessing that's a stale CSS cache on your end. The CSS class for highlighted redexes has been renamed, so highlights disappearing seems consistent with that. Try Ctrl+F5, and the highlights should appear again, along with the new ones in plug diagrams.
That logging call has been left on purpose, as it *should* be dead code, assuming no further `LambdaTerm` types are added, but I guess an exception would be more idiomatic.

**Comment by TwoFX** [comment]
Why does the first commit add the servlet jar to the repository?

**Comment by TehMillhouse** [comment]
Oops. The perils of `git commit -a`. Fixed.

**Comment by mhuisi** [comment]
You're right, the CSS cache was the issue. Sorry for that.
Some more feedback:

In the unicode output, clickable lambdas are marked in a different color, so you don't have to hover over every single one to find lambdas that you can click.
Additionally, the underline disappears when you hover over a clickable lambda, and the binding area of the redex is highlighted.
It would be great if plug diagrams behaved similarly: 
Clickable pacmans should be highlighted (`#009782` as well?) and when hovering over them, the binding area highlight for the redex that will be evaluated next by the selected evaluation stategy disappears (turns black), while the binding area highlight for the redex of the pacman you're hovering over appears.
I'm not sure if the binding area highlight for the redex you're hovering over should be a different color than the one that the evaluation strategy suggests.

Clickable pacmans being highlighted is a must in my opinion, however, I'd be fine with accepting the PR even if the other suggestions are missing.

**Comment by TwoFX** [comment]
Redexes where the left hand side is a named term are not clickable since they do not have a pacman symbol. Since this breaks the interactivity when named terms are involved, I think that some clickable doodad should be added in that situation.

**Comment by TehMillhouse** [comment]
A point of order: I don't expect these diagrams to be *completely* self-explanatory. The goal is to make substitution fool-proof (no shadowing, capture avoidance, missing parentheses), make the inherent structure of lambda terms explicit, and very obviously show that there is a fundamental semantic difference between a bound variable and a free variable. There... will be slides. 
> In the unicode output, clickable lambdas are marked in a different color, so you don't have to hover over every single one to find lambdas that you can click.

With text, we have it easy: make it blue, underline it, and people will click on it. Within a diagram, it's not so clear-cut, and I'm not convinced more colors would help :confused:. The reduction order's next redex is already highlighted, and the text says redexes can be clicked, so if that doesn't get people to hover over pacmans, more colors aren't going to, either.
One of the strengths of these diagrams compared to a textual representation is that you can locally decide whether something is a redex or not. I find it rather easy to visually differentiate a pacman that is "plugged into" an application from one that is not. Adding more colors to the diagrams tends to make the difference between the abstraction of a redex and "free" abstractions more jarring. I've played around with adding a surrounding line around plugged pacmans, but that already makes them too visually dissimilar.

> Additionally, the underline disappears when you hover over a clickable lambda, and the binding area of the redex is highlighted.
> It would be great if plug diagrams behaved similarly:
> Clickable pacmans should be highlighted (`#009782` as well?) and when hovering over them, the binding area highlight for the redex that will be evaluated next by the selected evaluation stategy disappears (turns black), while the binding area highlight for the redex of the pacman you're hovering over appears.

I'm 100% with you on these things, I just haven't spent much thought on how I can make it happen. Honestly, if adding the next-redex highlight and clickable redexes hadn't turned out much easier than I expected, I would have stopped at black-and-white renderings.

> I'm not sure if the binding area highlight for the redex you're hovering over should be a different color than the one that the evaluation strategy suggests.

Since the next-redex-highlight disappears while hovering, I don't see why there shouldn't just be a single "will be reduced" color.

> Clickable pacmans being highlighted is a must in my opinion, however, I'd be fine with accepting the PR even if the other suggestions are missing

Could we settle on "everything except clickable pacmans being highlighted"? :grimacing: 

> Redexes where the left hand side is a named term are not clickable since they do not have a pacman symbol. Since this breaks the interactivity when named terms are involved, I think that some clickable doodad should be added in that situation.

Agreed, will look into it.

**Comment by mhuisi** [comment]
> Within a diagram, it's not so clear-cut, and I'm not convinced more colors would help

I was thinking of something like this:
lambda

>so if that doesn't get people to hover over pacmans, more colors aren't going to, either.

I don't think clickable redexes are that obvious, and I've found myself just swiping my mouse over the plug diagram to see where the color changes to find redexes I can click. I suspect that it gets worse with bigger diagrams.

>Adding more colors to the diagrams tends to make the difference between the abstraction of a redex and "free" abstractions more jarring.

I'm not sure what you mean here.

>Since the next-redex-highlight disappears while hovering, I don't see why there shouldn't just be a single "will be reduced" color.

I agree, I was just considering it for consistency with the unicode output in the first place.

**Comment by TehMillhouse** [comment]
I propose a compromise...
screenshot from 2018-11-29 18-32-19
I can still fine-tune the opacity & blurriness of the glow, if it's not visible enough, hell, I can make it slowly *pulse*
madwithpower
*you could have prevented this*

**Comment by TwoFX** [comment]
Is it possible to transform the cursor into the hand-thing when hovering a clickable pacman?

**Comment by TehMillhouse** [comment]
After much soul-searching, I've come to the conclusion that instead of floating abstractions to the right, it's easier to flip applications. Normal order becomes simply "pushing things through arrows from left to right", and the transformation from text to diagram is easier to get right, since "flipping" is easier to convey than "floating", and because applications have handy borders around them.

> Is it possible to transform the cursor into the hand-thing when hovering a clickable redex?

Done.

I'm still fiddling with getting to feature parity with the unicode output.

**Comment by TehMillhouse** [comment]
That took longer than expected, but hovers are working now. Performance has gotten much worse, though I could fix that if it becomes a real issue (it's still faster than tree layout).
Next up: glow.
screenshot from 2018-12-07 18-16-19
Ignore the fact the pointer still looks like an arrow in the screenshot, that's due to the screenshotting tool.

**Comment by TehMillhouse** [comment]
Glowing clickable redexes are done, and [live](https://pp.ipd.kit.edu/lehre/misc/lambda-ide/Wavelength.html). Plug diagrams should now have feature parity with the unicode output.
Adding a new tree output based on the `SVGElement` infrastructure shouldn't be hard, either, if someone has a weekend to kill ;)

**Pull request merged**
